version: '3.7'

services:
  flask:
    build: .
    volumes:
      - ./templates:/templates
    ports:
      - 8081:8081
    depends_on:
      - memcached
    environment:
      - PORT=8081
      - DEBUG=False
  memcached:
    image: memcached:1.5.22-alpine
